name = "Takeoff"
license = "MIT"
licenselink = "https://github.com/crakjie/landing-page-hugo/blob/master/LICENSE.md"
description = "An elegant open source landing page theme."
homepage = "https://github.com/crakjie/landing-page-hugo"
tags = ["company", "products", "landing page"]
features = ["social", "images" ]
min_version= 0.14

[author]
    name = "larriant"

[original]
    author =  "crakjie"
    homepage = "https://github.com/crakjie/landing-page-hugo"
    repo = "https://github.com/crakjie/landing-page-hugo"

